swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport: '%env(MAILER_TRANSPORT)%'
    host:      '%env(MAILER_HOST)%'
    username:  '%env(MAILER_USER)%'
    password:  '%env(MAILER_PASSWORD)%'