---
services:
  elkarbackup:
    image: elkarbackup/elkarbackup:2.1.0
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      SYMFONY__DATABASE__PASSWORD: "your-password-here"
    #volumes:
    #- backups:/app/backups
    #- uploads:/app/uploads
    #- sshkeys:/app/.ssh
    ports:
      - 8000:80
    
  db:
    image: mariadb:lts
    environment:
      MARIADB_ROOT_PASSWORD: "your-password-here"
    volumes:
      - db:/var/lib/mysql

  #client:
  #  image: elkarbackup/client

volumes:
  db:
#  backups:
#  uploads:
#  sshkeys:
